//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTC.Reporting.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VTC.Reporting.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;col-sm-3&quot;&gt;.
        /// </summary>
        internal static string colSm3DivOpenTag {
            get {
                return ResourceManager.GetString("colSm3DivOpenTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;container&quot; id=&quot;main&quot;&gt;.
        /// </summary>
        internal static string containerDivOpenTag {
            get {
                return ResourceManager.GetString("containerDivOpenTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;docheader&quot;&gt;
        ///  &lt;h4&gt;Turn Movement Count &lt;/h4&gt;
        ///  &lt;h4&gt;&lt;span class=&quot;light&quot;&gt;Location: &lt;/span&gt;@location&lt;/h4&gt;
        ///  &lt;h4&gt;&lt;span class=&quot;light&quot;&gt;Date: &lt;/span&gt;@date&lt;/h4&gt;
        ///  &lt;/div&gt;.
        /// </summary>
        internal static string docHeader {
            get {
                return ResourceManager.GetString("docHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;footer&gt;
        ///  &lt;p&gt;Counts generated by &amp;nbsp; &lt;img id=&quot;logoicon&quot; src=&quot;./ReportAssets/favicon.ico&quot;&gt; VTC on @date&lt;/p&gt; 
        ///&lt;/footer&gt;.
        /// </summary>
        internal static string footer {
            get {
                return ResourceManager.GetString("footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script src=&quot;https://code.jquery.com/jquery-2.2.4.min.js&quot; &gt;&lt;/script&gt;
        ///  &lt;link rel=&quot;icon&quot; href=&quot;./ReportAssets/favicon.ico&quot;&gt;
        ///  &lt;link href=&quot;https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css&quot; rel=&quot;stylesheet&quot; integrity=&quot;sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7&quot; crossorigin=&quot;anonymous&quot;&gt;
        ///  &lt;script src=&quot;https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js&quot; integrity=&quot;sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS&quot; crossorigi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string headerString {
            get {
                return ResourceManager.GetString("headerString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;row text-center&quot;&gt;
        ///    &lt;img id=&quot;legend&quot; src=&quot;./RegionsLegend.png&quot;&gt;
        ///  &lt;/div&gt;.
        /// </summary>
        internal static string legendDiv {
            get {
                return ResourceManager.GetString("legendDiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;row top-buffer&quot; id=&quot;@rowid&quot;&gt;.
        /// </summary>
        internal static string rowTopBufferDivOpenTag {
            get {
                return ResourceManager.GetString("rowTopBufferDivOpenTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;row top-buffer collapse&quot; id=&quot;@rowid&quot;&gt;.
        /// </summary>
        internal static string rowTopBufferDivOpenTagCollapse {
            get {
                return ResourceManager.GetString("rowTopBufferDivOpenTagCollapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;rtsparkline&quot;&gt;@data&lt;/span&gt;.
        /// </summary>
        internal static string rtSparkline {
            get {
                return ResourceManager.GetString("rtSparkline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;col-sm-3&quot;&gt;
        ///	&lt;h4&gt;@approach&lt;/h4&gt;
        ///	Peak time: &lt;span class=&quot;summarystats&quot;&gt;@peaktime&lt;/span&gt;&lt;br&gt;
        ///	Peak flow: &lt;span class=&quot;summarystats&quot;&gt;@peakflow vehicles/5min&lt;/span&gt;&lt;br&gt;
        ///	Total flow: &lt;span class=&quot;summarystats&quot;&gt;@total vehicles&lt;/span&gt; &lt;br&gt;
        ///	Left: &amp;nbsp; &lt;span class=&quot;summarystats&quot;&gt;@left&lt;/span&gt; &lt;br&gt;
        ///	Right: &lt;span class=&quot;summarystats&quot;&gt;@right&lt;/span&gt; &lt;br&gt;
        ///	Thru: &amp;nbsp;&lt;span class=&quot;summarystats&quot;&gt;@thru&lt;/span&gt; &lt;br&gt;
        ///	UTurn: &lt;span class=&quot;summarystats&quot;&gt;@uturn&lt;/span&gt; &lt;br&gt;
        ///.
        /// </summary>
        internal static string summaryStatistics {
            get {
                return ResourceManager.GetString("summaryStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;col-sm-3&quot;&gt;
        ///	&lt;h4&gt;@approach&lt;/h4&gt;
        ///	Peak time: &lt;span class=&quot;summarystats&quot;&gt;@peaktime&lt;/span&gt;&lt;br&gt;
        ///	Peak flow: &lt;span class=&quot;summarystats&quot;&gt;@peakflow people/5min&lt;/span&gt;&lt;br&gt;
        ///	Total flow: &lt;span class=&quot;summarystats&quot;&gt;@total people&lt;/span&gt; &lt;br&gt;
        ///	Crossing: &amp;nbsp; &lt;span class=&quot;summarystats&quot;&gt;@crossing&lt;/span&gt; &lt;br&gt;
        ///	.
        /// </summary>
        internal static string summaryStatisticsSidewalk {
            get {
                return ResourceManager.GetString("summaryStatisticsSidewalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///    &lt;td  class=&quot;time&quot;&gt;@time&lt;/td&gt;
        ///    &lt;td&gt;@left&lt;/td&gt; 
        ///	&lt;td&gt;@right&lt;/td&gt; 
        ///	&lt;td&gt;@thru&lt;/td&gt; 
        ///    &lt;td&gt;@uturn&lt;/td&gt;
        ///  &lt;/tr&gt;.
        /// </summary>
        internal static string tableCountRow {
            get {
                return ResourceManager.GetString("tableCountRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///    &lt;td  class=&quot;time&quot;&gt;@time&lt;/td&gt;
        ///    &lt;td&gt;@crossing&lt;/td&gt;&lt;/tr&gt;.
        /// </summary>
        internal static string tableCountRowSidewalk {
            get {
                return ResourceManager.GetString("tableCountRowSidewalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///    &lt;td&gt;&lt;/td&gt;
        ///    &lt;td class=&quot;turnlabel&quot;&gt;Left&lt;/td&gt; 
        ///	&lt;td class=&quot;turnlabel&quot;&gt;Right&lt;/td&gt; 
        ///	&lt;td class=&quot;turnlabel&quot;&gt;Thru&lt;/td&gt; 
        ///	&lt;td class=&quot;turnlabel&quot;&gt;UTurn&lt;/td&gt; 
        ///  &lt;/tr&gt;.
        /// </summary>
        internal static string tableHeaderRow {
            get {
                return ResourceManager.GetString("tableHeaderRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///    &lt;td&gt;&lt;/td&gt;
        ///    &lt;td class=&quot;turnlabel&quot;&gt;Crossing&lt;/td&gt;&lt;/tr&gt;.
        /// </summary>
        internal static string tableHeaderRowSidewalk {
            get {
                return ResourceManager.GetString("tableHeaderRowSidewalk", resourceCulture);
            }
        }
    }
}
