//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTC.db {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VTC.db.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 1 FROM pg_database WHERE datname=&apos;roadometry&apos;.
        /// </summary>
        internal static string CheckIfDatabaseExistsSQL {
            get {
                return ResourceManager.GetString("CheckIfDatabaseExistsSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE DATABASE roadometry
        ///    WITH 
        ///    OWNER = postgres
        ///    ENCODING = &apos;UTF8&apos;
        ///    LC_COLLATE = &apos;English_United States.1252&apos;
        ///    LC_CTYPE = &apos;English_United States.1252&apos;
        ///    TABLESPACE = pg_default
        ///    CONNECTION LIMIT = -1;.
        /// </summary>
        internal static string CreateDatabaseSQL {
            get {
                return ResourceManager.GetString("CreateDatabaseSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE public.job
        ///(
        ///    created_at timestamp with time zone,
        ///    groundtruthpath path,
        ///    regionconfiguration text COLLATE pg_catalog.&quot;default&quot;,
        ///    videopath path,
        ///    id integer NOT NULL DEFAULT nextval(&apos;job_id_seq&apos;::regclass),
        ///    CONSTRAINT job_pkey PRIMARY KEY (id)
        ///)
        ///
        ///TABLESPACE pg_default;
        ///
        ///ALTER TABLE public.job
        ///    OWNER to postgres;.
        /// </summary>
        internal static string CreateJobTableSQL {
            get {
                return ResourceManager.GetString("CreateJobTableSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE public.movement
        ///(
        ///    id bigint NOT NULL DEFAULT nextval(&apos;movement_id_seq&apos;::regclass),
        ///    job_id integer NOT NULL DEFAULT nextval(&apos;movement_job_id_seq&apos;::regclass),
        ///    approach text COLLATE pg_catalog.&quot;default&quot;,
        ///    exit text COLLATE pg_catalog.&quot;default&quot;,
        ///    movementtype text COLLATE pg_catalog.&quot;default&quot;,
        ///    objecttype text COLLATE pg_catalog.&quot;default&quot;,
        ///    synthetic boolean,
        ///    CONSTRAINT movement_pkey PRIMARY KEY (id),
        ///    CONSTRAINT job_fkey FOREIGN KEY (job_id)
        ///        REFERENCES public [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateMovementTableSQL {
            get {
                return ResourceManager.GetString("CreateMovementTableSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE public.stateestimate
        ///(
        ///    id bigint NOT NULL DEFAULT nextval(&apos;stateestimate_id_seq&apos;::regclass),
        ///    movement_id bigint NOT NULL DEFAULT nextval(&apos;stateestimate_movement_id_seq&apos;::regclass),
        ///    x real,
        ///    y real,
        ///    vx real,
        ///    vy real,
        ///    red real,
        ///    blue real,
        ///    green real,
        ///    size real,
        ///    vsize real,
        ///    pathlength real,
        ///    CONSTRAINT stateestimate_pkey PRIMARY KEY (id),
        ///    CONSTRAINT movement_fkey FOREIGN KEY (movement_id)
        ///        REFERENCES public.movement (id) MATCH SIMPLE
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateStateEstimateTableSQL {
            get {
                return ResourceManager.GetString("CreateStateEstimateTableSQL", resourceCulture);
            }
        }
    }
}
