//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTC.db {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VTC.db.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreateJobIdSeqPostgresql {
            get {
                return ResourceManager.GetString("CreateJobIdSeqPostgresql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreateJobTablePostgresql {
            get {
                return ResourceManager.GetString("CreateJobTablePostgresql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE job (id INTEGER PRIMARY KEY, videopath TEXT, regionconfigurationname TEXT, groundtruthpath TEXT, timestamp TEXT).
        /// </summary>
        internal static string CreateJobTableSQLite {
            get {
                return ResourceManager.GetString("CreateJobTableSQLite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreateMovementIdSeqPostgresql {
            get {
                return ResourceManager.GetString("CreateMovementIdSeqPostgresql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreateMovementJobIdSeqPostgresql {
            get {
                return ResourceManager.GetString("CreateMovementJobIdSeqPostgresql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE movement (
        ///	id	INTEGER PRIMARY KEY,
        ///	jobid	INTEGER,
        ///	approach	TEXT,
        ///	exit	TEXT,
        ///	movementtype	TEXT,
        ///	trafficobjecttype	TEXT,
        ///	timestamp	TEXT,
        ///	synthetic	INTEGER,
        ///	ignored	INTEGER,
        ///	FOREIGN KEY(jobid) REFERENCES job(id)
        ///).
        /// </summary>
        internal static string CreateMovementTableSQLite {
            get {
                return ResourceManager.GetString("CreateMovementTableSQLite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreateMovementTableSQLPostgresql {
            get {
                return ResourceManager.GetString("CreateMovementTableSQLPostgresql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreateStateEstimateIdSeqPostgresql {
            get {
                return ResourceManager.GetString("CreateStateEstimateIdSeqPostgresql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreateStateEstimateMovementIdSeqPostgresql {
            get {
                return ResourceManager.GetString("CreateStateEstimateMovementIdSeqPostgresql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE stateestimate (
        ///	id	INTEGER PRIMARY KEY,
        ///	movementid	INTEGER,
        ///	x	REAL,
        ///	y	REAL,
        ///	vx	REAL,
        ///	vy	REAL,
        ///	red	REAL,
        ///	blue	REAL,
        ///	green	REAL,
        ///	size	REAL,
        ///	vsize	REAL,
        ///	pathlength	REAL,
        ///	FOREIGN KEY(movementid) REFERENCES movement(id)
        ///).
        /// </summary>
        internal static string CreateStateEstimateTableSQLite {
            get {
                return ResourceManager.GetString("CreateStateEstimateTableSQLite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreateStateEstimateTableSQLPostgresql {
            get {
                return ResourceManager.GetString("CreateStateEstimateTableSQLPostgresql", resourceCulture);
            }
        }
    }
}
